repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.30.0
    hooks:
      - id: golangci-lint
  - repo: https://github.com/prettier/prettier/
    rev: master
    hooks:
      - id: prettier
  - repo: local
    hooks:
      - id: unit-tests
        name: unit tests
        entry: go test ./...
        language: system
        files: \.go$
        types: [file]
        pass_filenames: false
